version: '3.6'

services:
  web:
    volumes:
      - "./web/src/:/app/"
      - "../tmp_webdav/:/tmp/webdav/:ro"
    ports:
      - "8177:8177"
    depends_on:
      - db

  nginx:
    volumes:
      - "./nginx/src/:/app/"
      - "../tmp_webdav/:/var/www/webdav/"
    ports:
      - "80:80"

  db:
    image: postgres:12.5
    environment:
      POSTGRES_DB: ekirill
      POSTGRES_USER: ekirill
      POSTGRES_PASSWORD: devpassword
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
