version: '3.6'

services:
  back:
    volumes:
      - "storage:/tmp/webdav/:ro"
      - "./back/src/:/app/"

  nginx:
    volumes:
      - "storage:/var/www/webdav/"
      - "./nginx/src/:/app/"
    ports:
      - "80:80"
