version: '3.6'

services:
  back:
    volumes:
      - "./back/src/:/app/"
    command: 
      - "uvicorn"
      - "ekirill.app:app"
      - "--host"
      - "0.0.0.0"
      - "--reload"
      - "--port"
      - "8176"
    ports:
      - "8176:8176"

  web:
    volumes:
      - "./web/src/:/app/"
    ports:
      - "8177:8177"
    depends_on:
      - db

  nginx:
    volumes:
      - "./nginx/src/:/app/"
    ports:
      - "80:80"

  db:
    image: postgres:12.5
    environment:
      POSTGRES_DB: ekirill
      POSTGRES_USER: ekirill
      POSTGRES_PASSWORD: devpassword
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
