version: '3.6'

services:
  back:
    volumes:
      - "/Users/ekirill/tmp/camera/:/tmp/webdav/:ro"
      - "./back/src/:/app/"
    command: ["uvicorn", "ekirill.app:app", "--host", "0.0.0.0", "--reload", "--port", "8176"]

  nginx:
    volumes:
      - "storage:/var/www/webdav/"
      - "./nginx/src/:/app/"
    ports:
      - "80:80"
