version: '3.6'

services:
  back:
    container_name: back
    build:
      context: ./back/
      dockerfile: docker/Dockerfile
    volumes:
      - storage:/tmp/webdav/:ro
    env_file: .env
    environment:
      - EKIRILL_CAMERA_VIDEODIR=/tmp/webdav/CAMERA/
      - EKIRILL_DB_DEFAULT_HOST=db
    expose:
      - "8176"
    command: ["uvicorn", "ekirill.app:app", "--host", "0.0.0.0", "--workers", "3", "--limit-concurrency", "10", "--port", "8176"]

  nginx:
    container_name: nginx
    build:
      context: ./nginx/
      dockerfile: docker/Dockerfile
    volumes:
      - storage:/var/www/webdav/
    env_file: .env
    environment:
      - EKIRILL_STORAGE_DIR=/var/www/webdav/
      - EKIRILL_LOG=/var/log/nginx/access.log
    depends_on:
      - back

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.4.2
    container_name: nginx-exporter
    restart: unless-stopped
    environment:
      - SCRAPE_URI=http://nginx/nginx_status
      - TELEMETRY_PATH=/metrics
      - NGINX_RETRIES=10
    ports:
      - "9113:9113"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

volumes:
  storage:
