version: '3.6'

services:
  back:
    container_name: back
    build:
      context: ./back/
      dockerfile: docker/Dockerfile
    volumes:
      - storage:/tmp/webdav/:ro
    env_file: .env
    environment:
      - EKIRILL_CAMERA_VIDEODIR=/tmp/webdav/
      - EKIRILL_DB_DEFAULT_HOST=db
    ports:
      - "8176:8176"
    networks:
      - ekirill
    command: ["uvicorn", "ekirill.app:app", "--host", "0.0.0.0", "--workers", "3", "--limit-concurrency", "10", "--port", "8176"]

  webdav:
    container_name: webdav
    build:
      context: ./webdav/
      dockerfile: docker/Dockerfile
    volumes:
      - storage:/tmp/webdav/
    env_file: .env
    ports:
      - "8178:80"
    environment:
      - EKIRILL_STORAGE_DIR=/tmp/webdav/
    networks:
      - ekirill

volumes:
  storage:

networks:
  ekirill:
