version: '3.6'

services:
  web:
    container_name: web
    build:
      context: ./web/
      dockerfile: docker/Dockerfile
    volumes:
      - storage:/tmp/webdav/:ro
    env_file: .env
    environment:
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=ekirill.settings
    expose:
      - "8177"
    command:
      - "uwsgi"
      - "--chdir=/app/"
      - "--check-static=/app/htdocs"
      - "--module=ekirill.wsgi:application"
      - "--master"
      - "--http=0.0.0.0:8177"
      - "--processes=2"
      - "--harakiri=300"
      - "--max-requests=5000"
      - "--enable-threads"
      - "--vacuum"

  nginx:
    container_name: nginx
    build:
      context: ./nginx/
      dockerfile: docker/Dockerfile
    volumes:
      - storage:/var/www/webdav/
    env_file: .env
    environment:
      - EKIRILL_STORAGE_DIR=/var/www/webdav/
      - EKIRILL_LOG=/var/log/nginx/access.log

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.4.2
    container_name: nginx-exporter
    restart: unless-stopped
    environment:
      - SCRAPE_URI=http://nginx/nginx_status
      - TELEMETRY_PATH=/metrics
      - NGINX_RETRIES=10
    ports:
      - "9113:9113"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  db:
    image: postgres:12.5
    environment:
      POSTGRES_DB: ekirill
      POSTGRES_USER: ${EKIRILL_WEB_DB_DEFAULT_USER}
      POSTGRES_PASSWORD: ${EKIRILL_WEB_DB_DEFAULT_PASSWORD}
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  storage:
  dbdata:
