version: '3.6'

services:
  back:
    volumes:
      - "./back/src/:/app/"
    command: 
      - "uvicorn"
      - "ekirill.app:app"
      - "--host"
      - "0.0.0.0"
      - "--reload"
      - "--port"
      - "8176"
    ports:
      - "8176:8176"

  web:
    volumes:
      - "./web/src/:/app/"
    ports:
      - "8177:8177"

  nginx:
    volumes:
      - "./nginx/src/:/app/"
    ports:
      - "80:80"
